language: cpp
script:
  - cmake
  - ctest -j2 -VV

compiler:
  - clang
  - gcc

matrix:
  include:
    - env: BUILD_TYPE=Release CPP=11 SYSTEM_LIBCXX=On
      os: osx
      compiler: 
        - clang

    - env: BUILD_TYPE=Release CPP=11 SYSTEM_LIBCXX=On
      os: linux
      compiler: 
        - gcc
