language: cpp

matrix:
  include:

    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release CPP=14 SYSTEM_LIBCXX=On

    - os: osx
      compiler: clang
      env: COMPILER='clang++' CPP=14 BUILD_TYPE='Debug'

    - os: linux
      compiler: gcc
      addons: &gcc6 {apt: {packages: [g++-6] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Release CPP=14 COMPILER_VER=6

    - os: linux
      compiler: gcc
      addons: *gcc6
      env: BUILD_TYPE=Debug CPP=14 COMPILER_VER=6

before_script:
  - export CXX=${CXX}-${COMPILER_VER}
  - export CC=${CC}-${COMPILER_VER}
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Wdev
  - cd build

script:
  - make -j 2
  - ctest -V -j 2