language: cpp
script:
  - cmake .
  - cmake --build .
  - ctest -j2 -VV

compiler:
  - clang
  - gcc

matrix:
  include:
    - env: BUILD_TYPE=Release CPP=14 SYSTEM_LIBCXX=On
      os: osx
      compiler: 
        - clang

    - env: BUILD_TYPE=Release CPP=14 SYSTEM_LIBCXX=On
      os: linux
      compiler: 
        - gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER='g++-6' BUILD_TYPE='Release'
