version: '1.0.{build}'

os: Visual Studio 2017

platform:
   - Win32
   - x64

configuration:
   - Debug
   - Release

before_build:
  - cmake -H. -Bbuild -A%PLATFORM%


build:
   project: build/pandora.sln
   parallel: true
   verbosity: minimal

test_script:
  - cd build
  - ctest -V -j 2 -C %CONFIGURATION%